version: '3.7'
services:
  redis:
    image: redis:alpine
    container_name: tms-koa-redis
    ports:
      - '6379:6379'

  mongodb:
    image: mongo:latest
    container_name: tms-koa-mongo
    ports:
      - '27017:27017'
    logging:
      driver: none
